#+TITLE: README
#+AUTHOR: adrian

* LIBRARY

This is the public repository for my various reading notes, a lifelong work-in-progress. The entire system is meant to serve my predilections and preferences. These notes are rough, messy, maybe a bit less accurate than desired, and as such are always subject to all sorts of modifications. 

I do not have any pretensions as to the value anyone else may find for this, and I do not intend to build this with other people's audience in mind. I may not even fully understood some of these stuff I read, and I admit to that.

In any case, if you are curious and wish to make sense of this ever growing org file, here's a guide on the content and structure of the repository.


* GUIDE

I mainly read history books, so that's what most of these books will be about. Specifically, there will be a lot of books on the First World War, as well as the history of Christianity and the history of science, among others.

Books are organized alphabetically. These are a mix of stuff I've read since 2017, when I started keeping track of my books. Books and notes are constantly added, as I consolidate both past and recent notes I've made across various media and note taking apps.

These notes are taken as I go through the books. Quotes are passages that piqued my interest and generally are ones that sound cool enough for me to preserve for posterity. I also try my best to pinpoint the author's main thesis, and directly quote them if possible.

Some books are heavily noted, some aren't. In general, books that I read and reread /after/ the Library file is created, will have more detailed notes. Additionally, I focus on noting down ideas and contexts, and less on minute details like people and dates.

Many minor errors and typos may take time to be corrected, or for such corrections to be pushed to commit.


* FUTURE

As I build this library, I will think of other "features" I can add to make this easier for me to peruse. 

Some ideas I'm considering for the immediate and near future:

- Highlighting the quotes I like most.

**** *CREATED: 26 MAY 2025*
**** *EDITOR: GNU EMACS 30.1*


